version: "3.9"

services:
  frontend:
    container_name: clicker-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.development
    volumes:
      - "./frontend:/app"
      - "/app/node_modules"
    expose:
      - "3000"
    environment:
      - REACT_APP_BASE_URL=/api
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_HOST=localhost
      - WDS_SOCKET_PORT=9000
      - WDS_SOCKET_PATH=/wds
      - NODE_OPTIONS=--openssl-legacy-provider
    networks:
      - clicker-network

  backend:
    container_name: clicker-backend
    build:
      context: ./backend
      dockerfile: Dockerfile.development
    volumes:
      - "./backend:/server"
      - "/server/node_modules"
    expose:
      - "8000"
    environment:
      - PORT=8000
      - MONGO_URI=mongodb://mongo:27017/counterdb
      - PLUGIN_HOST=plugin
      - PLUGIN_PORT=50051
      - RABBITMQ_URL=amqp://${BROKER_USER}:${BROKER_PASSWORD}@rabbitmq:5672
      - BROKER_EXCHANGE_NAME=clicker-events
    depends_on:
      - rabbitmq
    networks:
      - clicker-network

  plugin:
    container_name: clicker-plugin
    build:
      context: ./plugin
      dockerfile: Dockerfile.development
    expose:
      - "50051"
    environment:
      - PLUGIN_PORT=50051
    networks:
      - clicker-network

  mongo:
    image: mongo
    container_name: clicker-db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - clicker-network

  nginx:
    container_name: clicker-nginx
    image: nginx:stable-bullseye
    ports:
      - "9000:9000" # Expose Nginx on port 9000
    volumes:
      - ./nginx_gateway_development.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    networks:
      - clicker-network

  rabbitmq:
    container_name: clicker-broker
    image: rabbitmq:3.12-management-alpine
    volumes:
      - "./rabbit_data:/var/lib/rabbitmq/"
      - "./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf"
    ports:
      - "5672:5672"     # RabbitMQ messaging port
      - "15672:15672"   # RabbitMQ management UI port
    environment:
      - RABBITMQ_DEFAULT_USER=${BROKER_USER}
      - RABBITMQ_DEFAULT_PASS=${BROKER_PASSWORD}
    networks:
      - clicker-network

  history-service:
    container_name: clicker-history
    build:
      context: ./history-service
      dockerfile: Dockerfile.development
    volumes:
      - "./history-service:/app"
      - "/app/node_modules"
    environment:
      - RABBITMQ_URL=amqp://${BROKER_USER}:${BROKER_PASSWORD}@rabbitmq:5672
      - BROKER_EXCHANGE_NAME=clicker-events
    depends_on:
      - rabbitmq
    networks:
      - clicker-network

volumes:
  mongo_data:

networks:
  clicker-network:
    name: clicker-network
    driver: bridge

