version: "3.9"

services:
  frontend:
    container_name: clicker-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.development
    volumes:
      - "./frontend:/app"
      - "/app/node_modules"
    expose:
      - "3000"
    environment:
      - REACT_APP_BASE_URL=/api
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_HOST=localhost
      - WDS_SOCKET_PORT=9000
      - WDS_SOCKET_PATH=/wds

  backend:
    container_name: clicker-backend
    build:
      context: ./backend
      dockerfile: Dockerfile.development
    volumes:
      - "./backend:/server"
      - "/server/node_modules"
    expose:
      - "8000"
    environment:
      - PORT=8000
      - MONGO_URI=mongodb://mongo:27017/counterdb
      - PLUGIN_HOST=plugin
      - PLUGIN_PORT=50051

  plugin:
    container_name: clicker-plugin
    build:
      context: ./plugin
      dockerfile: Dockerfile.development
    expose:
      - "50051"
    environment:
      - PLUGIN_PORT=50051

  mongo:
    image: mongo
    container_name: clicker-db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  nginx:
    container_name: clicker-nginx
    image: nginx:stable-bullseye
    ports:
      - "9000:9000" # Expose Nginx on port 9000
    volumes:
      - ./nginx_gateway_development.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend

volumes:
  mongo_data:
