FROM node:lts-alpine3.18

WORKDIR /server

# Copy package.json and install dependencies
COPY package.json package-lock.json* ./
RUN npm install

# Copy application files
COPY . .

# Ensure plugin.proto is copied
COPY ./plugin.proto ./plugin.proto

# Expose the application port
EXPOSE 8000

# Start the application
CMD ["node", "server.js"]
